on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: install deps
        run: |
          sudo apt-get install make
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          go mod vendor

      - name: Build
        env:
          VERSION: ${{ github.ref }}
        run: |
          make build

      - name: Pack
        env:
          VERSION: ${{ github.ref }}
        run: |
          filename=smartlin-cli-${{ env.VERSION }}-macos.tgz
          tar -C smartlin-cli-macos -vzcf $filename bin/smartling.darwin
          shasum -a 256 $filename > $filename.sha256

          filename=smartlin-cli-${{ env.VERSION }}-linux.tgz
          tar -C smartlin-cli-linux -vzcf $filename bin/smartling.linux
          shasum -a 256 $filename > $filename.sha256

          filename=smartlin-cli-${{ env.VERSION }}-windows.zip
          zip -j $filename bin/smartling.windows.exe
          shasum -a 256 $filename > $filename.sha256

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref }}
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            smartlin-cli-${{ env.VERSION }}-windows.zip
            smartlin-cli-${{ env.VERSION }}-windows.zip.sha256
            smartlin-cli-${{ env.VERSION }}-linux.tgz
            smartlin-cli-${{ env.VERSION }}-linux.tgz.sha256
            smartlin-cli-${{ env.VERSION }}-windows.zip
            smartlin-cli-${{ env.VERSION }}-windows.zip.sha256