on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: install deps
        run: |
          sudo apt-get install make
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          go mod vendor

      - name: Get Tag version
        id: tag_version
        run: echo ::set-env name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Build
        run: |
          make build

      - name: Pack
        run: |
          filename=smartlin-cli-${{ env.VERSION }}-darwin.zip
          zip -j $filename bin/smartling.darwin
          shasum -a 256 $filename > $filename.sha256

          filename=smartlin-cli-${{ env.VERSION }}-linux.zip
          zip -j $filename bin/smartling.linux
          shasum -a 256 $filename > $filename.sha256

          filename=smartlin-cli-${{ env.VERSION }}-windows.zip
          zip -j $filename bin/smartling.windows.exe
          shasum -a 256 $filename > $filename.sha256

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            smartlin-cli-${{ env.VERSION }}-darwin.zip
            smartlin-cli-${{ env.VERSION }}-darwin.zip.sha256
            smartlin-cli-${{ env.VERSION }}-linux.zip
            smartlin-cli-${{ env.VERSION }}-linux.zip.sha256
            smartlin-cli-${{ env.VERSION }}-windows.zip
            smartlin-cli-${{ env.VERSION }}-windows.zip.sha256